export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_SYS_ID = 'SET_SYS_ID'
export const SET_TENANT_ID = 'SET_TENANT_ID'
export const SET_FOLD = 'SET_FOLD'
