const meuns = [
  {
    appKid: '2001',
    component: 'bhsystemSetting',
    hidden: false,
    icon: 'icon-ziliao1',
    leaf: true,
    menuCode: 'bhsystemSetting',
    menuDesc: '',
    menuId: '2005291700099660001',
    menuName: '系统管理',
    menuView: '',
    params: '',
    parentKid: '0',
    path: '/bhsystemSetting',
    prefix: 'http://',
    query: '',
    sortNum: 0,
    target: '_self'
  },
  {
    appKid: '2001',
    component: 'bhBasicSettings',
    hidden: false,
    icon: 'icon-ziliao1',
    leaf: true,
    menuCode: 'bhBasicSettings',
    menuDesc: '',
    menuId: '2006151828452810001',
    menuName: '基础管理',
    menuView: '',
    params: '',
    parentKid: '0',
    path: '/bhBasicSettings',
    prefix: 'http://',
    query: '',
    sortNum: 1,
    target: '_self'
  },
  {
    appKid: '2001',
    component: 'bhQuotaManagement',
    hidden: false,
    icon: 'icon-ziliao1',
    leaf: true,
    menuCode: 'bhQuotaManagement',
    menuDesc: '',
    menuId: '2006151952146220001',
    menuName: '额度管理',
    menuView: '',
    params: '',
    parentKid: '0',
    path: '/bhQuotaManagement',
    prefix: 'http://',
    query: '',
    sortNum: 3,
    target: '_self'
  },
  {
    appKid: '2001',
    component: 'suretyCompany',
    hidden: false,
    icon: 'icon-danxuan',
    leaf: true,
    menuCode: 'suretyCompany',
    menuDesc: '',
    menuId: '2006151819208820001',
    menuName: '担保公司信息',
    menuView: '',
    params: '',
    parentKid: '2005291700099660001',
    path: '/bhsystemSetting/suretyCompany',
    prefix: 'http://',
    query: '',
    sortNum: 0,
    target: '_self'
  },
  {
    appKid: '2001',
    component: 'organization',
    hidden: false,
    icon: 'icon-danxuan',
    leaf: true,
    menuCode: 'organization',
    menuDesc: '',
    menuId: '2006301044025230001',
    menuName: '组织机构管理',
    menuView: '',
    params: '',
    parentKid: '2005291700099660001',
    path: '/bhsystemSetting/organization',
    prefix: 'http://',
    query: '',
    sortNum: 1,
    target: '_self'
  },
  {
    appKid: '2001',
    component: 'approvalRelation',
    hidden: false,
    icon: 'icon-danxuan',
    leaf: true,
    menuCode: 'approvalRelation',
    menuDesc: '',
    menuId: '2006151822020550001',
    menuName: '绑定审批关系',
    menuView: '',
    params: '',
    parentKid: '2005291700099660001',
    path: '/bhsystemSetting/approvalRelation',
    prefix: 'http://',
    query: '',
    sortNum: 2,
    target: '_self'
  }
]
export default meuns
